name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'

filter-by-commitish: true
commitish: main

categories:
    - title: Frontend New Features 🛠
      label: 'frontend'
    - title: Backend New Features 🛠
      label: 'backend'
    - title: Common library changes 🎊
      labels:
          - 'common-libs'

version-resolver:
    major:
        labels:
            - 'back-breaking-changes'
    minor:
        labels:
            - 'back-minor-changes'
    default: patch

include-labels:
    - 'frontend
    - 'backend'
    - 'common-libs'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

header: |
    ## What's Changed

template: |
    $CHANGES
